# https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "rust-opendingux-test",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[profile.test]
panic = "abort"

[profile.bench]
panic = "abort"
